### PR TITLE
[WIP] Delayed and planned for 1.19.3 (release, or beta, nor alpha)

### PR DESCRIPTION
**Pull request by ghost**
Planned or awaiting for 1.19.3 beta or release. Unofficial bug tracking and discussion: 

- https://github.com/hydra2s/reasonable-sorting/discussions/2
- https://github.com/SolidBlock-cn/reasonable-sorting/issues/16 (official issue, closed)

### CODE REVIEW

**Comment by lillythedeveloper** [comment]
very good 👍

**Comment by ghost** [comment]
I'm closed PR, due inactivity of author and commits bloat. Also, we waiting for 1.19.3 and official release (or beta).

**Comment by SolidBlock-cn** [comment]
Thank you for the commits. I'll consider your commits and plan to port to 1.19.3 before long.

**Comment by ghost** [comment]
I don't more planned to port RS for 22w46a or beyond. And client again crashed in that snapshot.

**Comment by SolidBlock-cn** [comment]
I'm sorry to say that your code is too confusing and there are many redundant statements in the code. It may take quite a while to merge your branch. I'll try the best.

**Comment by ghost** [comment]
How you planned to implement in 1.19.3?

**Comment by SolidBlock-cn** [comment]
I actually have no concrete plans to implement in 1.19.3. Actually I gave up 1.19.3 of this mod.

**Comment by ghost** [comment]
I'm very busy at the moment, and the year is coming to an end, time is running out. I need to prepare a rendering library for the Vulkan API.

**Pull request closed without merging**
